CREATE DATABASE xj6yh2xuacgp5ykb;

USE xj6yh2xuacgp5ykb;

CREATE TABLE burgers (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  burger_name VARCHAR(50) UNIQUE NOT NULL,
  devoured BOOL NOT NULL DEFAULT 0
);